language: python
python:
- '3.5'
- '3.6'
install:
- pip install django
script:
- python -c "__import__('sys').exit(0)"
deploy:
  provider: pypi
  user: isik-kaplan
  skip_existing: true
  password:
    secure: hErD9PlQy/Un9OMfryMKbwhF6gN5llA3PnJoVqj3LcrjglLmB/yD8z6jQ2PHvmL2QaxECps9JSj4s1W/CkyBWl6M0EYTXUT/Bl6a1nGJkrP4qM4VoLL1kPSX1/Lw85Jhmvzqm8SGYYcDTh0WI6nJNS3dibzSC1Qg6wGvYRdNAJmahnN9m1vMjvWfulNxerIOpAI03FESzA6iMsi0Hn2x07PtZCI/k2ox5fUgxQ5n1rqix2WkChzj0bFuBfn37JeD4lsC6E1lnz3/dfjVgxuzocAnukUv8Dv1RO1pLOnNmmUl2/oxIZH//uZLSWz2uIwtVCQYrzzoEjLbnBY2UUvMh4CBTrPr6/kbeY0YrFycl041RElQN9qWsNq64un3WjKkGbpR6czi07s8Ug5JwZ7o6e1X9EGhaXz5dn9HquqS54IFRhqNYbPdc6zDXGax1jjKpoaPMeKNKudKlWXWpAfCqlEX/MYc+PUn+Sqlv847pW5G9BxPphekqeyX+Ak61B6NeQs4OImLfqRIlWNlWzTUjkDcqj62DcSQC9BuDHgmq6F4q7dtI6icclkVYAFPr3HdrIfbhQ7RWSIomoEjUaBuhpD3g+EG7Y2jrfextSWdTDYx7gr1zlQC+R/BtoFTCEYNGTsVFOsIlgDJCojeQjLzNe3K5EIwpRetks9iXqwNzhk=
