language: python

dist: xenial

sudo: required

python:
  - '3.5'
  - '3.6'
  - '3.7'

install:
  - pip install tox-travis

script: tox

after_success:
  - codecov --flags "py${TRAVIS_PYTHON_VERSION//./}"