language: python
python:
- '3.5'
- '3.6'
install:
- pip install django
script:
- python -c "__import__('sys').exit(0)"
deploy:
  provider: pypi
  user: isik-kaplan
  skip_existing: true
  password:
    secure: W4SwYjaOMpz9ZZ419mJVlluMzf35R2W1sQmq2A7qTDqGlspX6eHlDGLz/0qZlzIumdOrxvqMhKRs7/mwh1zFMCAFOH4eruTM+ogrUu5yf5YPR01yRbuojRfnuWEdKQvxYzFKAcv/+lY91M8rnwVXB2LZ+uRNcBiuu+W5Zj9PA75axgLKo9p9zpsza9efkfDRhIMEdLv83Kf0yhQhEP4WJi4bLvtHMUx1YDecnXr1wR33DrvMYmYwQUzUmquSYi1ejLH3H3OXfWABNmr0/9NCJ1nLeJisePPygXiQZDd21Ao20jFnycTan3ZuXXefatdHTeRKYN/VrXz6HCjpqDFiN3iJ8rNhsN5J/acvV5xn8qgD+IXJ6c1/S79kATeP/JpHlkEPZblQL6kSAga6O5YdQQbKygrRKqa6jENdEW9UZWXOzqBS8lbzwGw740QKcnkDItMgXAw1sc5TZkJB4xxCgSBa9Bgm5knpbA2JKX9OnSlsXjDZN94226+HsO9jdFwdGsgG548UaxyCV6VmwSpsfNoI+CtOKmuKyeP2dO/6sl+3gGCRs+7/98GiQgLDZOilWCGoFksGskULDNBdcad0pvMBpETVqSMYcivgmxEPRYkxkzJBhVCkrqNSEJDCK3eGYE8mM/6VI7MsqxpIVn91CpoFFWxAqgFNh+mu9tyEdsk=
