language: python

dist: xenial

sudo: required

matrix:
  include:
    - python: '3.5'
      env: TOXENV=py35-django20
    - python: '3.6'
      env: TOXENV=py36-django20
    - python: '3.7'
      env: TOXENV=py37-django20

    - python: '3.5'
      env: TOXENV=py35-django21
    - python: '3.6'
      env: TOXENV=py36-django21
    - python: '3.7'
      env: TOXENV=py37-django21

    - python: '3.5'
      env: TOXENV=py35-django22
    - python: '3.6'
      env: TOXENV=py36-django22
    - python: '3.7'
      env: TOXENV=py37-django22

install:
  - pip install tox-travis
  - pip install codecov

script: tox

after_success:
  - codecov --flags "py${TRAVIS_PYTHON_VERSION//./}"

deploy:
  provider: pypi
  user: isik-kaplan
  skip_existing: true
  password:
    secure: LxReNt3cRQVWw6ehrEjWFmzbP3AEvB2E8sB6o+9zCJGMjVVMSch9Oxkk3762URIWQAtyAO53vdtKQaKDfVatumZFYIPoWv0UIgtCzmt0Kxhh93l5ItvuuMdU1MKnUBQrR986CjyTWOUnmDVNw2GgnHUIWPMa0ALzIupqikSyueFpt4syCQ4x9PIVjf+mto0Rx5dWcyYZx43xuE/sZwpiAOuMwelj3aMQFadui2+9N9A1VXpNtAe3Vich336fLZs5J8epdaRft/1p7gzBxCUUAV/iMc3FQoHMwP9YYfOMrOUZ1wZJmUY7AukyB4lIySmUB+xVPVsrN5zEQgo/dUzGeIRpShSEnDzgrGnJdQXk8iNipCu53FfhQdDQad/MQvSBmxWKYrqul2gD5iR0dlp/qYGdRWZ4m6kknFRUdbQlIC4pNmR14UTdYWnCABBEp1bbiiwdZPaMT+zICK2+6Op/UVg+UqBqdOEg6/KTesxncWBm3fLiDBz90zohR37mTGrJRIh4z4xihuGite0ZmZwA5Dd5VI/kHM/7VDLzdjJ/3mo8UJ0vKRTeUUCdaAPOTn7ZXm+cZ7Wp1ikcyICH29WEPNNsbvec2BYvhaEQv27ruvxTgRWyCB2pdlelpQ9fZo9GrXOFbbjkpGi6F/iANrlZkZYmN9u581J43LjYKgte9FU=
