language: python

dist: xenial

sudo: required

matrix:
  include:
    # Django 2.0
    - python: '3.5'
      env: TOXENV=py35-django20
    - python: '3.6'
      env: TOXENV=py36-django20
    - python: '3.7'
      env: TOXENV=py37-django20
    - python: '3.8'
      env: TOXENV=py38-django20

    # Django 2.1
    - python: '3.5'
      env: TOXENV=py35-django21
    - python: '3.6'
      env: TOXENV=py36-django21
    - python: '3.7'
      env: TOXENV=py37-django21
    - python: '3.8'
      env: TOXENV=py38-django21

    # Django 2.2
    - python: '3.5'
      env: TOXENV=py35-django22
    - python: '3.6'
      env: TOXENV=py36-django22
    - python: '3.7'
      env: TOXENV=py37-django22
    - python: '3.8'
      env: TOXENV=py38-django22

    # Django 3.0
    - python: '3.6'
      env: TOXENV=py36-django30
    - python: '3.7'
      env: TOXENV=py37-django30
    - python: '3.8'
      env: TOXENV=py38-django30
    - python: '3.9'
      env: TOXENV=py39-django30

    # Django 3.1
    - python: '3.6'
      env: TOXENV=py36-django31
    - python: '3.7'
      env: TOXENV=py37-django31
    - python: '3.8'
      env: TOXENV=py38-django31
    - python: '3.9'
      env: TOXENV=py39-django31

    # Django 3.2
    - python: '3.7'
      env: TOXENV=py37-django32
    - python: '3.8'
      env: TOXENV=py38-django32
    - python: '3.9'
      env: TOXENV=py39-django32
    - python: '3.10'
      env: TOXENV=py310-django32

    # Django 4.0
    - python: '3.8'
      env: TOXENV=py38-django40
    - python: '3.9'
      env: TOXENV=py39-django40
    - python: '3.10'
      env: TOXENV=py310-django40
    - python: '3.11'
      env: TOXENV=py311-django40

    # Django 4.1
    - python: '3.9'
      env: TOXENV=py39-django41
    - python: '3.10'
      env: TOXENV=py310-django41
    - python: '3.11'
      env: TOXENV=py311-django41
    - python: '3.12'
      env: TOXENV=py312-django41

    # Django 4.2
    - python: '3.10'
      env: TOXENV=py310-django42
    - python: '3.11'
      env: TOXENV=py311-django42
    - python: '3.12'
      env: TOXENV=py312-django42

    # Django 5.0
    - python: '3.10'
      env: TOXENV=py310-django50
    - python: '3.11'
      env: TOXENV=py311-django50
    - python: '3.12'
      env: TOXENV=py312-django50

    # Django 5.1
    - python: '3.10'
      env: TOXENV=py310-django51
    - python: '3.11'
      env: TOXENV=py311-django51
    - python: '3.12'
      env: TOXENV=py312-django51

install:
  - pip install --upgrade pip setuptools packaging  # Upgrade pip, setuptools, and packaging
  - pip install tox-travis
  - pip install codecov

script: tox

after_success:
  - codecov --flags "py${TRAVIS_PYTHON_VERSION//./}"

deploy:
  provider: pypi
  user: isik-kaplan
  skip_existing: true
  password:
    secure: LxReNt3cRQVWw6ehrEjWFmzbP3AEvB2E8sB6o+9zCJGMjVVMSch9Oxkk3762URIWQAtyAO53vdtKQaKDfVatumZFYIPoWv0UIgtCzmt0Kxhh93l5ItvuuMdU1MKnUBQrR986CjyTWOUnmDVNw2GgnHUIWPMa0ALzIupqikSyueFpt4syCQ4x9PIVjf+mto0Rx5dWcyYZx43xuE/sZwpiAOuMwelj3aMQFadui2+9N9A1VXpNtAe3Vich336fLZs5J8epdaRft/1p7gzBxCUUAV/iMc3FQoHMwP9YYfOMrOUZ1wZJmUY7AukyB4lIySmUB+xVPVsrN5zEQgo/dUzGeIRpShSEnDzgrGnJdQXk8iNipCu53FfhQdDQad/MQvSBmxWKYrqul2gD5iR0dlp/qYGdRWZ4m6kknFRUdbQlIC4pNmR14UTdYWnCABBEp1bbiiwdZPaMT+zICK2+6Op/UVg+UqBqdOEg6/KTesxncWBm3fLiDBz90zohR37mTGrJRIh4z4xihuGite0ZmZwA5Dd5VI/kHM/7VDLzdjJ/3mo8UJ0vKRTeUUCdaAPOTn7ZXm+cZ7Wp1ikcyICH29WEPNNsbvec2BYvhaEQv27ruvxTgRWyCB2pdlelpQ9fZo9GrXOFbbjkpGi6F/iANrlZkZYmN9u581J43LjYKgte9FU=
