language: python

dist: xenial

sudo: required

matrix:
  include:
    - python: '3.5'
      env: TOXENV=py35-django20
    - python: '3.6'
      env: TOXENV=py36-django20
    - python: '3.7'
      env: TOXENV=py37-django20

    - python: '3.5'
      env: TOXENV=py35-django21
    - python: '3.6'
      env: TOXENV=py36-django21
    - python: '3.7'
      env: TOXENV=py37-django21

    - python: '3.5'
      env: TOXENV=py35-django22
    - python: '3.6'
      env: TOXENV=py36-django22
    - python: '3.7'
      env: TOXENV=py37-django22

install:
  - pip install tox-travis
  - pip install codecov
script: tox

after_success:
  - codecov --flags "py${TRAVIS_PYTHON_VERSION//./}"