name: Django Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        django-version: ['4.0', '4.1', '4.2', '5.0', '5.1']
        os-version: [ubuntu-22.04]

    runs-on: ${{ matrix.os-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools packaging
          python -m pip install Django==${{ matrix.django-version }} pytest

      - name: Run Django tests
        run: |
          python test/manage.py test
